# Generated by Django 5.0.6 on 2024-06-01 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air_quality', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='data',
            name='pressure',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='wind_speed',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
