# Generated by Django 5.0.6 on 2024-06-01 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air_quality', '0004_alert_severity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='co2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='pm10',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='pm25',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
